### ISSUE TITLE
Share history with Command Line Interface?

### ISSUE THREAD

**Issue by Guillawme** [hanjinliu/Chimerax-clix#10]
This is a great add-on, thank you!
But it seems CliX has its own history, separate from the built-in Command Line Interface. Would it be possible to make it import the history from the built-in CLI? Or make the two share the same history?

**Comment by hanjinliu** [comment]
Hi @Guillawme ,
I totally agree with that! I think a method to import the history of built-in CLI is better for two reasons:
1. CliX supports multi-line, which is not shearable with the built-in CLI.
2. If there should be some breaking changes in the format ChimeraX uses for saving the command history in the future, CliX will crash ChimeraX itself.
I'll look for how ChimeraX saves its history and update CliX soon.
