### ISSUE TITLE
Auto-complete enumeration value

### ISSUE THREAD

**Issue by tomgoddard** [hanjinliu/Chimerax-clix#15]
In clix 0.1.4 if I type the following command

   volume #1 style surface

and press Enter it auto-completes surface to surface_smoothing which is a different keyword option and that gives an error since the "style" key word only takes values "surface", "mesh", "image" and "solid".  It would be nice if completion on a keyword value that is an enumerated type completed only to the allowed enumeration values.

**Comment by tomgoddard** [comment]
I see if I type a space after the word surface and press Enter then it works without changing surface to surface_smoothing.

**Comment by hanjinliu** [comment]
Hi @tomgoddard ,
thank you for reporting that! Yes, enumeration completion is absolutely an high-priority feature.
The issue you encountered is that `volume` command has `surface_smoothing` keyword, which was unexpectedly fired by the `surface` suffix. The "Enter" key is also assigned for accepting the current suggestion (if available). You can also type "Esc" to close the suggestion to avoid the completion.

**Comment by tomgoddard** [comment]
Is using "Enter" to accept command completion typical for other software?  A unix shell uses tab to accept a completion and Enter to actually run the command.   It seems a bit odd that running the command as typed without completion requires two steps Esc and Enter.  But I don't use completion in different software packages so I am not sure what is most common and what works best.

**Comment by hanjinliu** [comment]
That depends on the software and the widget design. For example, VSCode assign "Enter" and "Tab" to accept completion if it is shown as a tooltip, but only accept completion by clicking "Tab" if it is a inline suggestion (dim characters appearing after the cursor). Python console in ChimeraX does not show completion list until you type "Tab", and after the list is shown "Enter" is used for completion.

I think the behavior of "Enter" should be determined by the users. In the next release, I'll make it customizable by changing the preference.

**Comment by tomgoddard** [comment]
While it is nice to have an option to choose if Enter accepts a completion, I think few people will use that option.  So the most important thing is to get the default behavior to be the best.  I don't know what is best and will leave that to you.  I am one of the ChimeraX developers and I observe that ChimeraX users almost never change default settings.
