### ISSUE TITLE
Keystrokes from the graphics window

### ISSUE THREAD

**Issue by e-pettersen** [hanjinliu/Chimerax-clix#18]
The "regular" command line accepts keystrokes when the user has clicked into the main graphics window.  If would be nice if CliX could do the same.  It involves your tool calling session.ui.register_for_keystrokes(widget-that-wants-the key-events) and, when the tool is destroyed, session.ui.deregister_for_keystrokes(widget).  It's a tad more complex than that because the accepting widget may need to give itself the focus so that up/down arrow goes through the command history rather than changing the structure selection, and the keystroke-accepting routine should check session.ui.key_intercepted(event.key()) so that the function-key bundle can process function keys.  Anyway, you might want to look at keyPressEvent() in the embedded CmdText class in chimerax.cmd_line.tool.py to see what kind of monkey business goes on.  Feel free to ask questions if anything's too mystifying.

**Comment by hanjinliu** [comment]
Hi @e-pettersen ,
I think this feature is very important for better user experience.
I took a short look at the `CmdText` implementation. Does the keystroke in the graphics window send `forwarded=True` to the `keyPressEvent`?

**Comment by e-pettersen** [comment]
No, it calls widget.forwarded_keystroke(event).  The CmdText implements forwarded_keystroke() as a lambda that in turn calls keyPressEvent(event, forwarded=True).

**Comment by e-pettersen** [comment]
So the argument to register_for_keystrokes() doesn't have to be the widget necessarily.  It could be the tool, for instance, which would then take the event argument and forward it on to the appropriate widget.

**Comment by hanjinliu** [comment]
Thank you for the clarification. I think now I understand the behaviors of how GUI events are sent.
