### ISSUE TITLE
tooltip cut off

### ISSUE THREAD

**Issue by ajs99778** [hanjinliu/Chimerax-clix#23]
The tool looks great. One minor annoyance I've noticed is that the tooltip widget always shows below the command edit widget unless you're currently typing a keyword. This can lead to it getting cut off at the bottom on the screen (see image). I think it'd be better to always show above the command edit when it's this close to the bottom.

![image](https://github.com/hanjinliu/Chimerax-clix/assets/41082252/0db7d44e-7575-402a-b8d2-7edd7b9bf123)

**Comment by hanjinliu** [comment]
Hi @ajs99778 , that'll be a very nice improvement. Thanks for the idea!
